---
title: "Replication of Study 3a by García-Castro, Rodríguez-Bailón, & Willis (2020, Journal of Experimental Social Psychology)"
author: "Cedric Lim Chun Hui (limch@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

This paper contributes importantly to the understanding that any behavioral effect of economic inequality is contingent on people's perceptions. In addition, the study tests the novel prediction that perceptions of high inequality will lead to greater intolerance for inequality and increased support for redistributive policies. Perceived economic inequality is first manipulated, following which measures intolerance of inequality and support for economic redistribution are asked. There are two hypotheses for this study: (1) participants in the percevied economic inequality condition should show a higher intolerance of inequality than participants in the control condition, and (2) Intolerance of inequality would mediate the relationship between perceived economic inequality and support for economic redistribution.

This replication will take the form of a questionnaire. Both the manipulation and outcome measures are administered in the form of open-ended and multiple-choice questions. It is expected to take no more than 10 minutes to complete. Qualtrics will be the platform of choice and the study will be conducted on Prolific. Challenges include an unfamiliarity with using Prolific as a data collection platform, and whether we can avoid or filter out potential bots to ensure a real participant sample. Attention checks will be used to verify this as well. Another expected challenge will involve sourcing out the exact materials used in the original study as the article only provides broad details on some measures. It may be possible to obtain the exact materials from any form of supplemental materials, the preregistration document, or by contacting the authors directly.

[Link to Repository](https://github.com/psych251/garciacastro2020)

[Link to Original Paper](https://github.com/psych251/garciacastro2020/blob/main/original_paper/Garc%C3%ADa-Castro%20et%20al.%202020.pdf)

## Methods

### Power Analysis

An average effect size of *d*=0.32 was found across the studies (2,3a,3b) using the thought manipulation. G*Power suggests that a sample size of 244 is required to achieve 80% power to detect this effect size. However, due to financial limitations, we aim to collect data from at least 41 participants.

### Planned Sample

Participants are expected to take approximately 10 minutes to complete the study, to which they will be reimbursed \$1.20 (based on the average U.S. minimum wage). With a minimum funding of \$50, it guarantees a sample of at least 41 participants. The only inclusion criteria is that all participants must be from the U.S.

### Materials

**Thought Manipulation** - To manipulate perceived economic inequality, participants will be asked to think about the wealthiest and the least wealthy persons they know. Then, they are asked to write a paragraph about how economic resources influence the lives of the people they considered. In the control condition, participants are instead asked to think about the tallest and shortest persons they knew and how height influences their lives. 

*Experimental condition*: Please describe the person you know personally who has the most economic resources and the person you know personally who has the least economic resources. Think about what they can do and what not with the resources they have. Tell us how the economic resources influence their lives by writing at least one paragraph for each of these two people. 

*Control condition*: Please describe the person of the smallest height you know personally and the tallest person you know personally. Think about what they can do and what not with their height. Tell us how their height influence their lives by writing at least one paragraph for each of these two people.  

**Manipulation Check** - A single-item measure, "For the two people you have just thought about, how different do you think they are in terms of wealth?" Response options will range from *1 (not at all different) to 5 (extremely different)*. The higher the score, the greater the difference.

**Intolerance of Inequality** - A single item measure, "To what extent do you agree that the income differences in the U.S. are too large?" will be used (Gonthier, 2017; Larsen, 2016; Schröder, 2017). Response options range from *1 (totally disagree) to 7 (totally agree)*. The higher the score, the less tolerance to inequality.

**Support for Economic Redistribution** - Participants will respond to three items, (1) "The Government has the responsibility to reduce the income differences between those who have high incomes and those who have low incomes", (2) "The government should provide a decent standard of living for the unemployed", and (3) "The government should spend less on benefits for the poor" (ISSP, 2017). Response options range from *1 (completely disagree) to 7 (completely agree)*. The higher the score, the greater the support for redistributive policies.

### Procedure	

Participants will be randomly assigned to one of the two thought manipulation conditions, following which they will complete the manipulation check and the measures of intolerance of inequality and support for redistribution.

### Analysis Plan

Participants who fail an included attention check will be excluded from the analysis.

Hypothesis (1): An independent samples t-test will be conducted to see if there are significant differences between the two conditions on the manipulation check and the measure of intolerance of inequality. 

Hypothesis (2): A mediation analysis will be conducted to see if intolerance of inequality mediates the relationship between perceived economic inequality and support for redistributive policies. 

### Differences from Original Study

Unlike the original study which sampled from Spanish university students, participants for this replication effort will be recruited through the Prolific platform. 

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
